#!/bin/sh
# postrm script for mydombox

set -e

case "$1" in
    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)

	userdel -f mydombox
	udevadm trigger
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0