USE `mydombox`;

TRUNCATE TABLE type;

INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('1','1','10','Lighting 1', '00','','X10 lighting');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('2','1','10','Lighting 1', '01','','ARC');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('3','1','10','Lighting 1', '02','','ELRO AB400D (Flamingo)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('4','1','10','Lighting 1', '03','','Waveman');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('5','1','10','Lighting 1', '04','','Chacon EMW200');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('6','1','10','Lighting 1', '05','','IMPULS');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('7','1','10','Lighting 1', '06','','RisingSun');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('8','1','10','Lighting 1', '07','','Philips SBC');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('9','1','11','Lighting 2', '00','','AC,Chacon,DIO');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('10','1','11','Lighting 2', '01','','HomeEasy EU');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('11','1','11','Lighting 2', '02','','ANSLUT');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('12','1','14','Lighting 5', '00','','LightwaveRF, Siemens (AD protocol) ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('13','1','14','Lighting 5', '01','','EMW100 GAO/Everflourish');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('14','1','14','Lighting 5', '02','','BBSB new types ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('15','1','14','Lighting 5', '03','','MDREMOTE LED dimmer ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('16','1','14','Lighting 5', '04','','Conrad RSL2 ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('17','1','14','Lighting 5', '05','','Livolo');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('18','1','14','Lighting 5', '06','','RGB TRC02');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('19','1','1A','RFY', '00','','Somfy RTS');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('20','1','1A','RFY', '01','','Somfy RTS ext');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('21','1','40','Thermostat 1', '00','','Digimax, TLX7506');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('22','1','40','Thermostat 1', '01','','Digimax with short format');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('23','1','41','Thermostat 2', '00','','HomeEasy HE105');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('24','1','41','Thermostat 2', '01','','RTS10, RFS10, TLX1206');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('25','1','50','Temperature sensors', '01','','THR128/138, THC138');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('26','1','50','Temperature sensors', '02','','THC238/268,THN132,THWR288,THRN122,THN122,AW129/131');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('27','1','50','Temperature sensors', '03','','THWR800');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('28','1','50','Temperature sensors', '04','','RTHN318');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('29','1','50','Temperature sensors', '05','','La Crosse TX3, TX4, TX17');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('30','1','50','Temperature sensors', '06','','TS15C');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('31','1','50','Temperature sensors', '07','','Viking 02811');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('32','1','50','Temperature sensors', '08','','La Crosse WS2300');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('33','1','50','Temperature sensors', '09','','RUBiCSON');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('34','1','50','Temperature sensors', '0A','','TFA 30.3133');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('35','1','51','Humidity sensors', '01','','LaCrosse TX3');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('36','1','51','Humidity sensors', '02','','LaCrosse WS2300');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('37','1','52','Temperature and humidity sensors', '01','','THGN122/123, THGN132, THGR122/228/238/268');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('38','1','52','Temperature and humidity sensors', '02','','THGR810, THGN800');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('39','1','52','Temperature and humidity sensors', '03','','RTGR328');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('40','1','52','Temperature and humidity sensors', '04','','THGR328');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('41','1','52','Temperature and humidity sensors', '05','','WTGR800');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('42','1','52','Temperature and humidity sensors', '06','','THGR918, THGRN228, THGN50');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('43','1','52','Temperature and humidity sensors', '07','','TFA TS34C, Cresta');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('44','1','52','Temperature and humidity sensors', '08','','WT260,WT260H,WT440H,WT450,WT450H');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('45','1','52','Temperature and humidity sensors', '09','','Viking 02035, 02038');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('46','1','52','Temperature and humidity sensors', '0A','','Rubicson');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('47','1','52','Temperature and humidity sensors', '0B','','EW109 ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('48','1','52','Temperature and humidity sensors', '0C','','Imagintronix Soil sensor');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('49','1','54','Temperature, humidity and barometric sensors', '01','','BTHR918');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('50','1','54','Temperature, humidity and barometric sensors', '02','','BTHR918N, BTHR968');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('51','1','55','Rain sensors', '01','','RGR126/682/918');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('52','1','55','Rain sensors', '02','','PCR800');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('53','1','55','Rain sensors', '03','','TFA');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('54','1','55','Rain sensors', '04','','UPM RG700');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('55','1','55','Rain sensors', '05','','WS2300');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('56','1','56','Wind sensors', '01','','WTGR800');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('57','1','56','Wind sensors', '02','','WGR800');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('58','1','56','Wind sensors', '03','','STR918, WGR918');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('59','1','56','Wind sensors', '04','','TFA (WIND4)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('60','1','56','Wind sensors', '05','','UPM WDS500');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('61','1','56','Wind sensors', '06','','WS2300');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('62','1','57','UV sensors', '01','','UVN128, UV138');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('63','1','57','UV sensors', '02','','UVN800');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('64','1','57','UV sensors', '03','','TFA');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('65','1','58','Date/Time sensors', '01','','RTGR328N');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('66','1','59','Current sensors', '01','','CM113, Electrisave');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('67','1','5A','Energy usage sensors', '01','','CM119/160');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('68','1','5A','Energy usage sensors', '02','','CM180');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('69','1','14','Lighting 5', '00','','LightwaveRF, Siemens');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('70','1','14','Lighting 5', '01','','EMW100 GAO/Everflourish');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('71','1','14','Lighting 5', '02','','BBSB new types');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('72','1','14','Lighting 5', '03','','MDREMOTE LED dimmer');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('73','1','14','Lighting 5', '04','','Conrad RSL2');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('74','1','14','Lighting 5', '05','','Livolo');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('75','1','14','Lighting 5', '06','','RGB TRC02');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('76','2','ERDF','ERDF Tele', '01','','ERDF Monophase Counter');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('77','2','ERDF','ERDF Tele', '03','','ERDF Triphase Counter');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('78','3','1W28','One Wire Temperature', '01','','One Wire DS18B20');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('79','4','F6','EnOcean F6', '02','01','F6-02-01: Light and Blind Control - Application Style 1 ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('80','4','F6','EnOcean F6', '02','02','F6-02-02: Light and Blind Control - Application Style 2 ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('81','4','F6','EnOcean F6', '02','03','F6-02-03: Light Control - Application Style 1 ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('82','4','F6','EnOcean F6', '02','04','F6-02-04: Light and blind control ERP2');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('83','4','F6','EnOcean F6', '03','01','F6-03-01: Light and Blind Control - Application Style 1 ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('84','4','F6','EnOcean F6', '03','02','F6-03-02: Light and Blind Control - Application Style 2');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('85','4','F6','EnOcean F6', '04','01','F6-04-01: Key Card Activated Switch ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('86','4','F6','EnOcean F6', '04','02','F6-04-02: Key Card Activated Switch ERP2');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('87','4','F6','EnOcean F6', '05','01','F6-05-01: Liquid Leakage Sensor (mechanic harvester)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('88','4','F6','EnOcean F6', '10','00','F6-10-00: Window Handle');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('89','4','F6','EnOcean F6', '10','01','F6-10-01: Window Handle ERP2');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('90','4','D5','EnOcean D5', '00','01','D5-00-01: Single Input Contact');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('91','4','A5','EnOcean A5', '02','01','A5-02-01: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('92','4','A5','EnOcean A5', '02','02','A5-02-02: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('93','4','A5','EnOcean A5', '02','03','A5-02-03: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('94','4','A5','EnOcean A5', '02','04','A5-02-04: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('95','4','A5','EnOcean A5', '02','05','A5-02-05: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('96','4','A5','EnOcean A5', '02','06','A5-02-06: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('97','4','A5','EnOcean A5', '02','07','A5-02-07: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('98','4','A5','EnOcean A5', '02','08','A5-02-08: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('99','4','A5','EnOcean A5', '02','09','A5-02-09: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('100','4','A5','EnOcean A5', '02','0A','A5-02-0A: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('101','4','A5','EnOcean A5', '02','0B','A5-02-0B: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('102','4','A5','EnOcean A5', '02','10','A5-02-10: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('103','4','A5','EnOcean A5', '02','11','A5-02-11: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('104','4','A5','EnOcean A5', '02','12','A5-02-12: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('105','4','A5','EnOcean A5', '02','13','A5-02-13: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('106','4','A5','EnOcean A5', '02','14','A5-02-14: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('107','4','A5','EnOcean A5', '02','15','A5-02-15: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('108','4','A5','EnOcean A5', '02','16','A5-02-16: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('109','4','A5','EnOcean A5', '02','17','A5-02-17: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('110','4','A5','EnOcean A5', '02','18','A5-02-18: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('111','4','A5','EnOcean A5', '02','19','A5-02-19: Temperature ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('112','4','A5','EnOcean A5', '02','1A','A5-02-1A: Temperature');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('113','4','A5','EnOcean A5', '02','1B','A5-02-1B: Temperature');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('114','4','A5','EnOcean A5', '02','20','A5-02-20: 10 Bit Temperature Sensor Range -10 C to +41.2 C');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('115','4','A5','EnOcean A5', '02','30','A5-02-30: 10 Bit Temperature Sensor Range -40 C to +62.3 C ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('116','4','A5','EnOcean A5', '04','01','A5-04-01: Range 0 C to +40 C and 0% to 100%');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('117','4','A5','EnOcean A5', '04','02','A5-04-02: Range -20 C to +60 C and 0% to 100%');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('118','4','A5','EnOcean A5', '04','03','A5-04-03: Range -20 C to +60 C 10bit-measurement and 0% to 100%');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('119','4','A5','EnOcean A5', '05','01','A5-05-01: Range 500 to 1150 hPa');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('120','4','A5','EnOcean A5', '06','01','A5-06-01: Range 300lx to 60.000lx');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('121','4','A5','EnOcean A5', '06','02','A5-06-02: Range 0lx to 1.020lx');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('122','4','A5','EnOcean A5', '06','03','A5-06-03: 10-bit measurement (1-Lux resolution) with range 0lx to 1000lx ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('123','4','A5','EnOcean A5', '07','01','A5-07-01: Occupancy with Supply voltage monitor ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('124','4','A5','EnOcean A5', '07','02','A5-07-02: Occupancy with Supply voltage monitor');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('125','4','A5','EnOcean A5', '07','03','A5-07-03: Occupancy with Supply voltage monitor and 10-bit illumination measurement ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('126','4','A5','EnOcean A5', '08','01','A5-08-01: Range 0lx to 510lx, 0 C to +51 C and Occupancy Button ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('127','4','A5','EnOcean A5', '08','02','A5-08-02: Range 0lx to 1020lx, 0 C to +51 C and Occupancy Button ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('128','4','A5','EnOcean A5', '08','03','A5-08-03: Range 0lx to 1530lx, -30 C to +50 C and Occupancy Button');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('129','4','A5','EnOcean A5', '09','02','A5-09-02: CO-Sensor 0 ppm to 1020 ppm');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('130','4','A5','EnOcean A5', '09','04','A5-09-04: CO2 Sensor');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('131','4','A5','EnOcean A5', '09','05','A5-09-05: VOC Sensor');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('132','4','A5','EnOcean A5', '09','06','A5-09-06: Radon');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('133','4','A5','EnOcean A5', '09','07','A5-09-07: Particles');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('134','4','A5','EnOcean A5', '09','08','A5-09-08: Pure CO2 Sensor');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('135','4','A5','EnOcean A5', '09','09','A5-09-09: Pure CO2 Sensor with Power Failure Detection');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('136','4','A5','EnOcean A5', '10','01','A5-10-01: Temperature Sensor, Set Point, Fan Speed and Occupancy Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('137','4','A5','EnOcean A5', '10','02','A5-10-02: Temperature Sensor, Set Point, Fan Speed and Day/Night Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('138','4','A5','EnOcean A5', '10','03','A5-10-03: Temperature Sensor, Set Point Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('139','4','A5','EnOcean A5', '10','04','A5-10-04: Temperature Sensor, Set Point and Fan Speed Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('140','4','A5','EnOcean A5', '10','05','A5-10-05: Temperature Sensor, Set Point and Occupancy Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('141','4','A5','EnOcean A5', '10','06','A5-10-06: Temperature Sensor, Set Point and Day/Night Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('142','4','A5','EnOcean A5', '10','07','A5-10-07: Temperature Sensor, Fan Speed Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('143','4','A5','EnOcean A5', '10','08','A5-10-08: Temperature Sensor, Fan Speed and Occupancy Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('144','4','A5','EnOcean A5', '10','09','A5-10-09: Temperature Sensor, Fan Speed and Day/Night Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('145','4','A5','EnOcean A5', '10','0A','A5-10-0A: Temperature Sensor, Set Point Adjust and Single Input Contact');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('146','4','A5','EnOcean A5', '10','0B','A5-10-0B: Temperature Sensor and Single Input Contact');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('147','4','A5','EnOcean A5', '10','0C','A5-10-0C: Temperature Sensor and Occupancy Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('148','4','A5','EnOcean A5', '10','0D','A5-10-0D: Temperature Sensor and Day/Night Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('149','4','A5','EnOcean A5', '10','10','A5-10-10: Temperature and Humidity Sensor, Set Point and Occupancy Control ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('150','4','A5','EnOcean A5', '10','11','A5-10-11: Temperature and Humidity Sensor, Set Point and Day/Night Control ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('151','4','A5','EnOcean A5', '10','12','A5-10-12: Temperature and Humidity Sensor and Set Point');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('152','4','A5','EnOcean A5', '10','13','A5-10-13: Temperature and Humidity Sensor, Occupancy Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('153','4','A5','EnOcean A5', '10','14','A5-10-14: Temperature and Humidity Sensor, Day/Night Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('154','4','A5','EnOcean A5', '10','15','A5-10-15: 10 Bit Temperature Sensor, 6 bit Set Point Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('155','4','A5','EnOcean A5', '10','16','A5-10-16: 10 Bit Temperature Sensor, 6 bit Set Point Control;Occupancy Control ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('156','4','A5','EnOcean A5', '10','17','A5-10-17: 10 Bit Temperature Sensor, Occupancy Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('157','4','A5','EnOcean A5', '10','18','A5-10-18: Illumination, Temperature Set Point, Temperature Sensor, Fan Speed and Occupancy Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('158','4','A5','EnOcean A5', '10','19','A5-10-19: Humidity, Temperature Set Point, Temperature Sensor, Fan Speed and Occupancy Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('159','4','A5','EnOcean A5', '10','1A','A5-10-1A: Supply voltage monitor, Temperature Set Point, Temperature Sensor, Fan Speed and Occupancy Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('160','4','A5','EnOcean A5', '10','1B','A5-10-1B: Supply Voltage Monitor, Illumination, Temperature Sensor, Fan Speed and Occupancy Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('161','4','A5','EnOcean A5', '10','1C','A5-10-1C: Illumination, Illumination Set Point, Temperature Sensor, Fan Speed and Occupancy Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('162','4','A5','EnOcean A5', '10','1D','A5-10-1D: Humidity, Humidity Set Point, Temperature Sensor, Fan Speed and Occupancy Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('163','4','A5','EnOcean A5', '10','1E','A5-10-1E: see A5-10-1B');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('164','4','A5','EnOcean A5', '10','1F','A5-10-1F: Temperature Sensor, Set Point, Fan Speed, Occupancy and Unoccupancy Control');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('165','4','A5','EnOcean A5', '10','20','A5-10-20: Temperature and Set Point with Special Heating States');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('166','4','A5','EnOcean A5', '10','21','A5-10-21: Temperature, Humidity and Set Point with Special Heating States');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('167','4','A5','EnOcean A5', '11','01','A5-11-01: Lighting Controller');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('168','4','A5','EnOcean A5', '11','02','A5-11-02: Temperature Controller Output');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('169','4','A5','EnOcean A5', '11','03','A5-11-03: Blind Status');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('170','4','A5','EnOcean A5', '11','04','A5-11-04: Extended Lighting Status');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('171','4','A5','EnOcean A5', '12','00','A5-12-00: Counter');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('172','4','A5','EnOcean A5', '12','01','A5-12-01: Electricity');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('173','4','A5','EnOcean A5', '12','02','A5-12-02: Gas');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('174','4','A5','EnOcean A5', '12','03','A5-12-03: Water');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('175','4','A5','EnOcean A5', '12','04','A5-12-04: Temperature and Load Sensor ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('176','4','A5','EnOcean A5', '12','05','A5-12-05: Temperature and Container Sensor');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('177','4','A5','EnOcean A5', '13','01','A5-13-01: Weather Station');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('178','4','A5','EnOcean A5', '13','02','A5-13-02: Sun Intensity');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('179','4','A5','EnOcean A5', '13','03','A5-13-03: Date Exchange');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('180','4','A5','EnOcean A5', '13','04','A5-13-04: Time and Day Exchange ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('181','4','A5','EnOcean A5', '13','05','A5-13-05: Direction Exchange ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('182','4','A5','EnOcean A5', '13','06','A5-13-06: Geographic Position Exchange ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('183','4','A5','EnOcean A5', '13','10','A5-13-10: Sun position and radiation');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('184','4','A5','EnOcean A5', '14','01','A5-14-01: Single Input Contact (Window/Door), Supply voltage monitor');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('185','4','A5','EnOcean A5', '14','02','A5-14-02: Single Input Contact (Window/Door), Supply voltage monitor and Illumination');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('186','4','A5','EnOcean A5', '14','03','A5-14-03: Single Input Contact (Window/Door), Supply voltage monitor and Vibration ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('187','4','A5','EnOcean A5', '14','04','A5-14-04: Single Input Contact (Window/Door), Supply voltage monitor, Vibration and Illumination');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('188','4','A5','EnOcean A5', '14','05','A5-14-05: Vibration/Tilt, Supply voltage monitor');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('189','4','A5','EnOcean A5', '14','06','A5-14-06: Vibration/Tilt, Illumination and Supply voltage monitor');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('190','4','A5','EnOcean A5', '20','01','A5-20-01: Battery Powered Actuator (BI-DIR)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('191','4','A5','EnOcean A5', '20','02','A5-20-02: Basic Actuator (BI-DIR)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('192','4','A5','EnOcean A5', '20','03','A5-20-03: Line powered Actuator (BI-DIR)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('193','4','A5','EnOcean A5', '20','04','A5-20-04: Heating Radiator Valve Actuating Drive with Feed and Room Temperature Measurement, Local Set Point Control and Display (BI-DIR)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('194','4','A5','EnOcean A5', '20','10','A5-20-10: Generic HVAC Interface (BI-DIR)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('195','4','A5','EnOcean A5', '20','11','A5-20-11: Generic HVAC Interface-Error Control (BI-DIR)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('196','4','A5','EnOcean A5', '20','12','A5-20-12: Temperature Controller Input');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('197','4','A5','EnOcean A5', '30','01','A5-30-01: Single Input Contact, Battery Monitor ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('198','4','A5','EnOcean A5', '30','02','A5-30-02: Single Input Contact');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('199','4','A5','EnOcean A5', '30','03','A5-30-03: 4 Digital Inputs, Wake and Temperature');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('200','4','A5','EnOcean A5', '30','04','A5-30-04: 3 Digital Inputs, 1 Digital Input 8 Bits');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('201','4','A5','EnOcean A5', '37','01','A5-37-01: Demand Response');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('202','4','A5','EnOcean A5', '38','08','A5-38-08: Gateway');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('203','4','A5','EnOcean A5', '38','09','A5-38-09: Extended Lighting-Control 17.');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('204','4','A5','EnOcean A5', '3F','00','A5-3F-00: Radio Link Test (BI-DIR)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('205','4','D2','EnOcean D2', '00','01','D2-00-01: RCP with Temperature Measurement and Display (BI-DIR)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('206','4','D2','EnOcean D2', '01','00','D2-01-00: Type 0x00');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('207','4','D2','EnOcean D2', '01','01','D2-01-01: Type 0x01');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('208','4','D2','EnOcean D2', '01','02','D2-01-02: Type 0x02');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('209','4','D2','EnOcean D2', '01','03','D2-01-03: Type 0x03');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('210','4','D2','EnOcean D2', '01','04','D2-01-04: Type 0x04');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('211','4','D2','EnOcean D2', '01','05','D2-01-05: Type 0x05');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('212','4','D2','EnOcean D2', '01','06','D2-01-06: Type 0x06');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('213','4','D2','EnOcean D2', '01','07','D2-01-07: Type 0x07');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('214','4','D2','EnOcean D2', '01','08','D2-01-08: Type 0x08');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('215','4','D2','EnOcean D2', '01','09','D2-01-09: Type 0x09');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('216','4','D2','EnOcean D2', '01','0A','D2-01-0A: Type 0x0A (description: see table)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('217','4','D2','EnOcean D2', '01','0B','D2-01-0B: Type 0x0B (description: see table)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('218','4','D2','EnOcean D2', '01','10','D2-01-10: Type 0x10 (description: see table)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('219','4','D2','EnOcean D2', '01','11','D2-01-11: Type 0x11 (description: see table)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('220','4','D2','EnOcean D2', '02','00','D2-02-00: Type 0x00');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('221','4','D2','EnOcean D2', '02','01','D2-02-01: Type 0x01 (description: see table)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('222','4','D2','EnOcean D2', '02','02','D2-02-02: Type 0x02 (description: see table)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('223','4','D2','EnOcean D2', '03','00','D2-03-00: Type 0x00');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('224','4','D2','EnOcean D2', '03','10','D2-03-10: Mechanical Handle');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('225','4','D2','EnOcean D2', '04','00','D2-04-00: Type 0x00');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('226','4','D2','EnOcean D2', '04','01','D2-04-01: Type 0x01');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('227','4','D2','EnOcean D2', '04','02','D2-04-02: Type 0x02');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('228','4','D2','EnOcean D2', '04','03','D2-04-03: Type 0x03');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('229','4','D2','EnOcean D2', '04','04','D2-04-04: Type 0x04');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('230','4','D2','EnOcean D2', '04','05','D2-04-05: Type 0x05');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('231','4','D2','EnOcean D2', '04','06','D2-04-06: Type 0x06');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('232','4','D2','EnOcean D2', '04','07','D2-04-07: Type 0x07');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('233','4','D2','EnOcean D2', '04','08','D2-04-08: Type 0x08');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('234','4','D2','EnOcean D2', '04','09','D2-04-09: Type 0x09');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('235','4','D2','EnOcean D2', '04','10','D2-04-10: Type 0x10');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('236','4','D2','EnOcean D2', '04','1A','D2-04-1A: Type 0x1A (description: see table)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('237','4','D2','EnOcean D2', '04','1B','D2-04-1B: Type 0x1B (description: see table)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('238','4','D2','EnOcean D2', '04','1C','D2-04-1C: Type 0x1C (description: see table)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('239','4','D2','EnOcean D2', '04','1D','D2-04-1D: Type 0x1D (description: see table)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('240','4','D2','EnOcean D2', '04','1E','D2-04-1E: Type 0x1E (description: see table)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('241','4','D2','EnOcean D2', '05','00','D2-05-00: Type 0x00');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('242','4','D2','EnOcean D2', '10','00','D2-10-00: Type 0x00');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('243','4','D2','EnOcean D3', '10','01','D2-10-01: Type 0x01');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('244','4','D2','EnOcean D2', '10','02','D2-10-02: Type 0x02');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('245','4','D2','EnOcean D2', '20','01','D2-20-01: Type 0x01');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('246','4','D2','EnOcean D2', '20','02','D2-20-02: Type 0x02');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('247','4','D2','EnOcean D2', '30','00','D2-30-00: Type 0x00');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('248','4','D2','EnOcean D2', '30','01','D2-30-01: Type 0x01');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('249','4','D2','EnOcean D2', '30','02','D2-30-02: Type 0x02');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('250','4','D2','EnOcean D2', '30','03','D2-30-03: Type 0x03');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('251','4','D2','EnOcean D2', '30','04','D2-30-04: Type 0x04');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('252','4','D2','EnOcean D2', '30','05','D2-30-05: Type 0x05');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('253','4','D2','EnOcean D2', '30','06','D2-30-06: Type 0x06');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('254','4','D2','EnOcean D2', '31','00','D2-31-00: Type 0x00');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('255','4','D2','EnOcean D2', '31','01','D2-31-01: Type 0x01 (description: see table)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,type,subdescription) VALUES ('256','4','D2','EnOcean D2', 'A0','01','D2-A0-01: Valve Control (BI-DIR)');


DROP TABLE IF EXISTS `interfaces`;

CREATE TABLE `interfaces` (
`int_id` tinyint(3) unsigned NOT NULL,
`int_name` varchar(16) NOT NULL,
UNIQUE KEY `int_id` (`int_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `interfaces` VALUES (1,'RFXTRX433E'),(2,'RPIDOM TELE'),(3,'RPIDOM 1 WIRE'),(4,'ENOCEAN USB300');

