USE `mydombox`;

TRUNCATE TABLE type;

INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('1','1','10','Lighting 1', '00','X10 lighting');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('2','1','10','Lighting 1', '01','ARC');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('3','1','10','Lighting 1', '02','ELRO AB400D (Flamingo)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('4','1','10','Lighting 1', '03','Waveman');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('5','1','10','Lighting 1', '04','Chacon EMW200');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('6','1','10','Lighting 1', '05','IMPULS');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('7','1','10','Lighting 1', '06','RisingSun');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('8','1','10','Lighting 1', '07','Philips SBC');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('9','1','11','Lighting 2', '00','AC,Chacon,DIO');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('10','1','11','Lighting 2', '01','HomeEasy EU');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('11','1','11','Lighting 2', '02','ANSLUT');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('12','1','14','Lighting 5', '00','LightwaveRF, Siemens (AD protocol) ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('13','1','14','Lighting 5', '01','EMW100 GAO/Everflourish');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('14','1','14','Lighting 5', '02','BBSB new types ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('15','1','14','Lighting 5', '03','MDREMOTE LED dimmer ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('16','1','14','Lighting 5', '04','Conrad RSL2 ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('17','1','14','Lighting 5', '05','Livolo');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('18','1','14','Lighting 5', '06','RGB TRC02');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('19','1','1A','RFY', '00','Somfy RTS');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('20','1','1A','RFY', '01','Somfy RTS ext');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('21','1','40','Thermostat 1', '00','Digimax, TLX7506');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('22','1','40','Thermostat 1', '01','Digimax with short format');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('23','1','41','Thermostat 2', '00','HomeEasy HE105');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('24','1','41','Thermostat 2', '01','RTS10, RFS10, TLX1206');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('25','1','50','Temperature sensors', '01','THR128/138, THC138');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('26','1','50','Temperature sensors', '02','THC238/268,THN132,THWR288,THRN122,THN122,AW129/131');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('27','1','50','Temperature sensors', '03','THWR800');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('28','1','50','Temperature sensors', '04','RTHN318');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('29','1','50','Temperature sensors', '05','La Crosse TX3, TX4, TX17');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('30','1','50','Temperature sensors', '06','TS15C');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('31','1','50','Temperature sensors', '07','Viking 02811');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('32','1','50','Temperature sensors', '08','La Crosse WS2300');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('33','1','50','Temperature sensors', '09','RUBiCSON');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('34','1','50','Temperature sensors', '0A','TFA 30.3133');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('35','1','51','Humidity sensors', '01','LaCrosse TX3');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('36','1','51','Humidity sensors', '02','LaCrosse WS2300');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('37','1','52','Temperature and humidity sensors', '01','THGN122/123, THGN132, THGR122/228/238/268');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('38','1','52','Temperature and humidity sensors', '02','THGR810, THGN800');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('39','1','52','Temperature and humidity sensors', '03','RTGR328');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('40','1','52','Temperature and humidity sensors', '04','THGR328');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('41','1','52','Temperature and humidity sensors', '05','WTGR800');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('42','1','52','Temperature and humidity sensors', '06','THGR918, THGRN228, THGN50');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('43','1','52','Temperature and humidity sensors', '07','TFA TS34C, Cresta');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('44','1','52','Temperature and humidity sensors', '08','WT260,WT260H,WT440H,WT450,WT450H');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('45','1','52','Temperature and humidity sensors', '09','Viking 02035, 02038');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('46','1','52','Temperature and humidity sensors', '0A','Rubicson');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('47','1','52','Temperature and humidity sensors', '0B','EW109 ');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('48','1','52','Temperature and humidity sensors', '0C','Imagintronix Soil sensor');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('49','1','54','Temperature, humidity and barometric sensors', '01','BTHR918');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('50','1','54','Temperature, humidity and barometric sensors', '02','BTHR918N, BTHR968');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('51','1','55','Rain sensors', '01','RGR126/682/918');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('52','1','55','Rain sensors', '02','PCR800');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('53','1','55','Rain sensors', '03','TFA');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('54','1','55','Rain sensors', '04','UPM RG700');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('55','1','55','Rain sensors', '05','WS2300');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('56','1','56','Wind sensors', '01','WTGR800');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('57','1','56','Wind sensors', '02','WGR800');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('58','1','56','Wind sensors', '03','STR918, WGR918');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('59','1','56','Wind sensors', '04','TFA (WIND4)');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('60','1','56','Wind sensors', '05','UPM WDS500');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('61','1','56','Wind sensors', '06','WS2300');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('62','1','57','UV sensors', '01','UVN128, UV138');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('63','1','57','UV sensors', '02','UVN800');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('64','1','57','UV sensors', '03','TFA');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('65','1','58','Date/Time sensors', '01','RTGR328N');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('66','1','59','Current sensors', '01','CM113, Electrisave');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('67','1','5A','Energy usage sensors', '01','CM119/160');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('68','1','5A','Energy usage sensors', '02','CM180');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('69','1','14','Lighting 5', '00','LightwaveRF, Siemens');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('70','1','14','Lighting 5', '01','EMW100 GAO/Everflourish');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('71','1','14','Lighting 5', '02','BBSB new types');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('72','1','14','Lighting 5', '03','MDREMOTE LED dimmer');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('73','1','14','Lighting 5', '04','Conrad RSL2');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('74','1','14','Lighting 5', '05','Livolo');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('75','1','14','Lighting 5', '06','RGB TRC02');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('76','2','ERDF','ERDF Tele', '01','ERDF Monophase Counter');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('77','2','ERDF','ERDF Tele', '03','ERDF Triphase Counter');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('78','2','1W28','One Wire Temperature', '01','One Wire DS18B20');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('79','0','WP','Wifipower', '01','WP-PANEL-REL2');
INSERT IGNORE INTO type (type_id,int_id,packettype, packetdescription, subtype,subdescription) VALUES ('80','0','WP','Wifipower', '02','WP-PANEL-REL4');
