/* soapClient.c
   Generated by gSOAP 2.8.15 from mydombox-2.0.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.15 2013-07-28 20:17:04 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getLightingStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getLightingStatus *ns1__getLightingStatus, struct _ns1__getLightingStatusResponse *ns1__getLightingStatusResponse)
{	struct __ns1__getLightingStatus soap_tmp___ns1__getLightingStatus;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8888/";
	if (soap_action == NULL)
		soap_action = "http://mydombox.com/mydombox/getLightingStatus";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getLightingStatus.ns1__getLightingStatus = ns1__getLightingStatus;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getLightingStatus(soap, &soap_tmp___ns1__getLightingStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getLightingStatus(soap, &soap_tmp___ns1__getLightingStatus, "-ns1:getLightingStatus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getLightingStatus(soap, &soap_tmp___ns1__getLightingStatus, "-ns1:getLightingStatus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getLightingStatusResponse)
		return soap_closesock(soap);
	soap_default__ns1__getLightingStatusResponse(soap, ns1__getLightingStatusResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getLightingStatusResponse(soap, ns1__getLightingStatusResponse, "ns1:getLightingStatusResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__setLightingStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__setLightingStatus *ns1__setLightingStatus, struct _ns1__setLightingStatusResponse *ns1__setLightingStatusResponse)
{	struct __ns1__setLightingStatus soap_tmp___ns1__setLightingStatus;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8888/";
	if (soap_action == NULL)
		soap_action = "http://mydombox.com/mydombox/setLightingStatus";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__setLightingStatus.ns1__setLightingStatus = ns1__setLightingStatus;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__setLightingStatus(soap, &soap_tmp___ns1__setLightingStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__setLightingStatus(soap, &soap_tmp___ns1__setLightingStatus, "-ns1:setLightingStatus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__setLightingStatus(soap, &soap_tmp___ns1__setLightingStatus, "-ns1:setLightingStatus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__setLightingStatusResponse)
		return soap_closesock(soap);
	soap_default__ns1__setLightingStatusResponse(soap, ns1__setLightingStatusResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__setLightingStatusResponse(soap, ns1__setLightingStatusResponse, "ns1:setLightingStatusResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__initDevice(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__initDevice *ns1__initDevice, struct _ns1__initDeviceResponse *ns1__initDeviceResponse)
{	struct __ns1__initDevice soap_tmp___ns1__initDevice;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8888/";
	if (soap_action == NULL)
		soap_action = "http://mydombox.com/mydombox/initDevice";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__initDevice.ns1__initDevice = ns1__initDevice;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__initDevice(soap, &soap_tmp___ns1__initDevice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__initDevice(soap, &soap_tmp___ns1__initDevice, "-ns1:initDevice", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__initDevice(soap, &soap_tmp___ns1__initDevice, "-ns1:initDevice", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__initDeviceResponse)
		return soap_closesock(soap);
	soap_default__ns1__initDeviceResponse(soap, ns1__initDeviceResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__initDeviceResponse(soap, ns1__initDeviceResponse, "ns1:initDeviceResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
