#!/bin/sh
# postrm script for mydombox

set -e

case "$1" in
    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)

	rm -Rf /var/log/mydombox
	userdel -f mydombox
	udevadm trigger
    ;;

    upgrade)

        echo "postrm: Nothing to do on upgrade"
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0