#!/bin/sh
# postinst script for mydombox-display

echo "@xset s off" > /etc/xdg/lxsession/LXDE/autostart
echo "@xset -dpms" >> /etc/xdg/lxsession/LXDE/autostart
echo "@xset s noblank" >> /etc/xdg/lxsession/LXDE/autostart
echo "@chromium --noerrdialogs --kiosk http://127.0.0.1/mydombox-mobile/ --incognito" >> /etc/xdg/lxsession/LXDE/autostart

reboot
