#!/bin/sh
### BEGIN INIT INFO
# Provides:          mydombox
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mydombox Deamon
### END INIT INFO

sleep 10

set -e

# Must be a valid filename
NAME=mydombox
APPDIR=/usr/bin
PIDFILE=/var/run/mydombox.pid
DAEMON="$APPDIR/$NAME"
DEAMON_CONF=/etc/mydombox/mydombox.conf
DAEMON_OPTS="$DEAMON_CONF"
USER=mydombox

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

touch $PIDFILE
chown $USER: $PIDFILE

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
        start-stop-daemon --start --chdir $APPDIR --quiet --background --chuid $USER \
                        --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
        echo "."
        ;;
  stop)
        echo -n "Stopping daemon: "$NAME
        start-stop-daemon --stop --chdir $APPDIR --quiet --chuid $USER --oknodo --pidfile $PIDFILE
        echo "."
        ;;
  status)
        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
  restart)
        echo -n "Restarting daemon: "$NAME
        start-stop-daemon --stop --chdir $APPDIR --quiet --chuid $USER --oknodo --retry 30 --pidfile $PIDFILE
        start-stop-daemon --start --chdir $APPDIR --quiet --background --chuid $USER \
                        --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
        echo "."
        ;;

  *)
        echo "Usage: "$1" {start|stop|status|restart}"
        exit 1
esac
